### ISSUE TITLE
ember install ember-electron fails

### ISSUE THREAD

**Issue by ChasingLogic** [felixrieseberg/ember-electron#74]
When installing via `ember install ember-electron` I get the following error:

```bash
projects/electric master λ ember install ember-electron
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
The package `ember-electron` is not a properly formatted package, we have used a fallback lookup to resolve it at `/home/chasinglogic/projects/electric/node_modules/ember-electron`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The `ember-electron` addon could not be found at `/home/chasinglogic/projects/electric/node_modules/ember-electron`.
!! projects/electric master Δ 
````

And I cannot run the new ember generators etc because I continually get the same error.

**Comment by ChasingLogic** [comment]
Installing the git version of ember-electron appears to resolve this issue but I'm not familiar enough with Node yet to tell you why. If you need any additional info let me know:

OS: Fedora Linux 24
Node Version: 4.4.5
Npm version: 2.15.5
Ember-cli version: 2.6.2

**Comment by ruohki** [comment]
where did you clone the files does not work for me as well

**Comment by ChasingLogic** [comment]
@ruohki I used the git feature of npm if you change the line: `"ember-electron": "1.7.0"` to `"ember-electron": "git://github.com/felixreseberg/ember-electron"` then remove it from node_modules and npm install again it will at least install. Even after running `ember g ember-electron` however I'm unable to get it to actually work. I've gone to using electron directly.

**Comment by ruohki** [comment]
gotta try that still gotta figure out where to put the bps's to bad i dont have a slightly older version to look it up

**Comment by jacobq** [comment]
I'm almost certain this is related to a bad publish. See https://github.com/npm/npm/issues/5082
The reason I suspect this is that for me, `ember install ember-electron@git://github.com/felixrieseberg/ember-electron.git#v1.7.0` works while `ember install ember-electron@1.7.0` does not, and the only other time I had this happen it was caused by a bad publish (npm's fault).

**Comment by felixrieseberg** [comment]
Hey everyone, thanks for reporting this - it seems that the publish was indeed corrupted. I just pushed the existing version (same code and everything again) as `1.7.1` and I *really* hope that it'll fix everyone's trouble - I just installed it fine.

**Comment by ruohki** [comment]
works

**Comment by DDoSed** [comment]
I have same problem when I named folder with project "ember-electron" (like package name).
Just rename folder and it works.

I dont know maybe its normal (that you must not use the same name), I newbie at this party).

**Comment by decoded4620** [comment]
I'm having this issue now with a fresh app using newest ```ember```, and newest ```ember-electron```
```ember new my-cool-app``` 
```ember install ember-electron```

```ember -v```

```ember-cli: 2.9.1
node: 4.2.6
os: win32 ia32```

outputs the following error:

```ember g ember-electron```
```Block-scoped declarations (let, const, function, class) not yet supported outside strict mode```
```SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Function.Blueprint.load (Z:\EmberApps\node_modules\ember-cli\lib\models\blueprint.js:1276:29)
    at Function.Blueprint.lookup (Z:\EmberApps\node_modules\ember-cli\lib\models\blueprint.js:1253:24)
    at CoreObject.module.exports [as beforeRun] (Z:\EmberApps\node_modules\ember-cli\lib\utilities\merge-blueprint-options.js:24:27)
    at CLI.<anonymous> (Z:\EmberApps\node_modules\ember-cli\lib\cli\cli.js:124:13)
    at tryCatch (Z:\EmberApps\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (Z:\EmberApps\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (Z:\EmberApps\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (Z:\EmberApps\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:419:9)```

When and If i can solve this problem, I'll post my solution here as well. I haven't added or modified any code, just using the built in CLI commands to try and start a basic project. That should work out of the box without hassle!

**Comment by decoded4620** [comment]
In reference to my post above ^^. I've updated my system's Node and Npm installation (by just installing the newest node version 6.9.1). This removed all the old Node installed files and replaced it with new ones (according to the installer). 

Sadly although this "fixed" this issue, I'm still not sure as to WHY it fixed the issue.
